plugins {
    id 'java'
    id 'application'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
    maven { url = "https://raw.githubusercontent.com/jacamo-lang/mvn-repo/master" }
    maven { url = "https://jade.tilab.com/maven/" } 
}

dependencies {
    implementation 'io.github.jason-lang:jason-interpreter:3.2.0'
    implementation 'org.glassfish:jakarta.json:1.1.6'
}

sourceSets {
    main {
        java {
            srcDirs = ['src/java']
        }
    }
}

application {
    mainClass = 'Main'
}

compileJava.options.encoding = 'UTF-8'

tasks.named('run') {
    args 'grid_agent.mas2j'
    standardInput = System.in
}
